version: '3'

services:
  api:
    build:
      context: .
      dockerfile: local.Dockerfile
      args:
        TZ: ${TZ}
        USERNAME: ${DOCKER_USERNAME:-hoge}
        BUILD_COMMANDLINE_ARGS: ${BUILD_COMMANDLINE_ARGS}
        COMMANDLINE_ARGS: ${COMMANDLINE_ARGS}
        USER_UID: 9999
        USER_GID: 9999
    image: ${DOCKER_IMAGE}-local
    container_name: ${DOCKER_IMAGE}-api
    shm_size: '12gb'
    user: ${DOCKER_USERNAME}
    ports:
      - "${PORT:-7860}:${PORT:-7860}"
    volumes:
      - ./outputs:/outputs
      - ./log:/log
      - ./cache:/home/${DOCKER_USERNAME}/.cache
      - ./keys:/home/${DOCKER_USERNAME}/${API_DIR}/keys
    env_file:
      - .env
      - .env.local
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             capabilities: [gpu]
    command: ./webui.sh
    networks:
      - ${DOCKER_NETWORK}
networks:
  sd-webui-for-ml-local:
     external: true
